### ISSUE TITLE
Fails to build with lts-16

### ISSUE THREAD

**Issue by dpwiz** [theam/tintin#74]
```
tintin                           > configure (lib + exe)
tintin                           > Configuring tintin-1.10.1...
tintin                           > build (lib + exe)
tintin                           > Preprocessing library for tintin-1.10.1..
tintin                           > Building library for tintin-1.10.1..
tintin                           > [ 1 of 18] Compiling Paths_tintin
tintin                           > 
tintin                           > /home/user/src/os/tintin/.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.0.1.0/build/autogen/Paths_tintin.hs:15:1: error:
tintin                           >     parse error on input ‘#’
tintin                           >    |
tintin                           > 15 | #if defined(VERSION_base)
tintin                           >    | ^
```

Anything else I can post to help?

**Comment by bsaul** [comment]
I was able to get around this error by adding the following to `package.yaml`:

```
library:
    ... stuff ...
  # Work around compile error
  # See https://github.com/sol/hpack#handling-of-paths_-modules
  when:
  - condition: false
    other-modules: Paths_tintin
```

I got this from [here](https://github.com/mcwitt/tintin/blob/master/package.yaml#L66).
